services:
  - type: web
    name: fstail-api
    env: node
    plan: free
    buildCommand: >
  npm install --legacy-peer-deps --ignore-scripts
  && ./node_modules/.bin/prisma generate --schema=prisma/schema.prisma
  && cd apps/api && npm run buildstartCommand: cd apps/api && node dist/main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile